name: Build Solution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: nuget restore Archipelago.MultiClient.Net.sln
      
    - name: Build Library
      run: msbuild Archipelago.MultiClient.Net.sln
      
    - name: Download NUnit.ConsoleRunner.zip
      run: |
       Invoke-WebRequest https://github.com/nunit/nunit-console/releases/download/3.13.1/NUnit.Console-3.13.1.zip -OutFile NUnit.zip
       Expand-Archive -Path NUnit.zip -DestinationPath C:\NUnit
     
    - name: Run TestRunner
      run: |
       C:\NUnit\bin\net35\nunit3-console.exe Archipelago.MultiClient.Net.sln
       
    - name: Upload Test Results
      uses: actions/upload-artifact@v2.3.1
      with:
        name: TestResults
        path: TestResults.xml
    
